version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  test:
    build: .
    depends_on:
      - db
    env_file:
      - .env
      - .env.local
    volumes_from:
      - bundle
    volumes:
      - .:/app
      - ../:/src
    tty: true
    stdin_open: true
  bundle:
    image: busybox
    volumes:
      - /bundle
volumes:
  postgres:
  bundle:
  src:
