# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800a08b24795baa438b18054062e0a0fb3f3d59366f7b46ae402e5dd6c74a48d0f45f9bed157a2e24606dd003eacec1f2ec312e838b0ddefb93d9c8ae4803430

test:
  secret_key_base: 3aeacd6d61bc94f6a12613ccc2b5ea69eb273df123613d67475691ebc78a16d84129185d39b5ea57262fd60da12a2e72411d13a03fd5a419e36f7f3eb5b37fda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
